version: '3'

services:
  web:
    build: ./api
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./api:/app
      - bundle:/usr/local/bundle
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
  front: 
    build: ./front
    cpu_quota: 20000
    volumes:
      - ./front:/app
      - node_module_volumes:/app/node_modules
    ports:
      - '8080:3000'
    tty: true
    stdin_open: true
    command: yarn start

volumes:
  mysql_data:
  bundle:
  node_module_volumes: